name: Deploy to Hosting

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter branch name to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  deploy-prod:
    environment: prod
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Execute git pull on hosting
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} \
          "cd ${{ secrets.SERVER_DIR }} && git pull origin main"

  deploy-dev:
    environment: dev
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Execute git pull on development
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} \
          "cd ${{ secrets.SERVER_DIR_DEV }} && git pull origin ${{ github.event.inputs.branch }}"
